query GetUser($login: String!) {
  user(login: $login) {
    id
    login
    displayName
    description
    createdAt
    roles {
      isPartner
    }
    stream {
      id
      title
      type
      viewersCount
      createdAt
      game {
        name
      }
    }
  }
}
