query GetTopStreams($amount: Int!, $after: Cursor!) {
  streams(first: $amount, after: $after) {
    edges {
      cursor
      node {
        id
        title
        viewersCount
        language
        broadcaster {
          displayName
        }
        tags {
          id
          localizedName
        }
        game {
          name
        }
      }
    }
  }
}
