name: Testing

on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [13.x, 14.0.x, 14.x, 16.x]

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i --dev
    - run: npm test
